GET http://localhost:5209/user/test

###
POST http://localhost:5209/user/test
Content-Type: application/json

{
"Firstname": "Norwin",
"Lastname" : "Nabong",
"Email" : "norwin.nabong@skybest.com.ph",
"Username" : "nnabong",
"Password" : "skyNorwin01",
"Access" : "hehe"
}

### POST a new user
POST http://localhost:5209/user/test
Content-Type: application/json

{
  "Firstname": "Norwin",
  "Lastname": "Nabong",
  "Email": "norwin.nabong@skybest.com.ph",
  "Username": "nnabong",
  "Password": "skyNorwin01",
  "Access": "hehe"
}


###
GET http://localhost:5209

### GET all users
GET http://localhost:5209/user/test
Accept: application/json

###

### POST a new user
POST http://localhost:5209/user/test
Content-Type: application/json

{
  "Firstname": "Norwin",
  "Lastname": "Nabong",
  "Email": "norwin.nabong@skybest.com.ph",
  "Username": "nnabong",
  "Password": "skyNorwin01",
  "Access": "hehe"
}
